### ISSUE TITLE
Support for ingress with multiple paths

### ISSUE THREAD

**Issue by koalalorenzo** [cloudflare/cloudflare-ingress-controller#10]
Any plan to fix this?

` 1 controller.go:145] Cannot create tunnel for ingress with multiple paths`

**Comment by ntfrnzn** [comment]
multiple hostnames vs multiple paths

The ingress controller, as implemented, establishes a connecting tunnel between a single cloudflare-zone hostname and a single kubernetes service without interpreting any aspect of the traffic. Supporting multiple hostnames will require multiple tunnels, so it seems reasonable to require different ingress objects in that case. Multiple paths, on the other hand, simply requires interpreting the traffic after it exits the tunnel on the client/cluster side. This is feasible.

Desired behavior (as I understand it)
```
https://service.acme-cloudflare.com/alpha/abcd  --> warp-tunnel-1 --> http://alpha.some-ns/abcd
https://service.acme-cloudflare.com/beta/defg  --> warp-tunnel-1 --> http://beta.some-ns/defg
```
with all traffic transiting the same tunnel, being partitioned by path, with some path interpretation.

**Comment by mattalberts** [comment]
@bkeroackdsc I've been able to make headway on this as part of the 0.6.x release. You can at least specify multiple rules

**Comment by mattalberts** [comment]
Alright, the latest version, 0.6.0 supports multiple `rules` and `paths`
- `spec.rules[*]`
- `spec.rules[*].host.http.paths[*]` 

http paths, `path` (url path) based sub-routing in not supported.  The field is ignored (any url path presented is ignored and treated a "/").

I'm going to close this issue and open a different issue for url path based routing
