### ISSUE TITLE
ingress.class is being ignored

### ISSUE THREAD

**Issue by cbuckley01** [cloudflare/cloudflare-ingress-controller#124]
Just gave 0.6 a whirl and it appears that ingress.class support is broken, I've updated the cmdline to `---ingress-class=argo-tunnel`  and the controller is attempting to build tunnels for other ingresses that do not match its ingress.class, this is a log entry for my Jenkins ingress, which does not have a `kubernetes.io/ingress.class` defined and should be untouched by the argo controller:

`time="2018-11-29T17:33:06Z" level=error msg="link exited with error (*errors.errorString) 'Server error: Failed to update CNAME', repairing ..." hostname=jenkins.<MYDOMAIN> origin="jenkins-web.jenkins:80"`

**Comment by mattalberts** [comment]
interesting!

**Comment by mattalberts** [comment]
@cbuckley01 I've tagged a new release and updated the helm charts.
