### ISSUE TITLE
JSON logging

### ISSUE THREAD

**Issue by posix4e** [cloudflare/cloudflare-ingress-controller#138]
Would it be possible to have cloudflare output json logs instead of the current format?

**Comment by mattalberts** [comment]
That would likely be better for elk or splunk ingestion.  The logging is largely outside of my control at the moment (either dominated by glog'ing within-in kubernetes or logrus'ing with-in cloudflared).  Both offer some ability to configure a JSON writer or formatter respectively; though, you'd likely only get something of the format:

```console
{"level":"info","msg":"Tremendously sized cow enters the ocean.","time":"2014-03-10 19:57:38.562527896 -0400 EDT"}
```
> *note*: the entire log line would be in message as `cloudflared` does not use a field logger internally

**Comment by jbergstroem** [comment]
An optional `label` would be nice as well in case you run multiple ingresses.
