### ISSUE TITLE
32-bit ARM support

### ISSUE THREAD

**Issue by engenb** [cloudflare/cloudflare-ingress-controller#140]
Hello,

I've built a K8s cluster out of Raspberry PIs that I would love to get set up with the argo ingress controller.  Any thoughts around including a linux/arm (non-x64) docker image?

**Comment by mattalberts** [comment]
@engenb 
I'm pretty certain I did all the work to support 32bit arm; I just didn't have a way to test it :) You want to try?
 - `mattalberts/argo-tunnel-arm32v6:0.6.3`

**Comment by mattalberts** [comment]
I'll preemptively create the PR assuming everything works 👍

**Comment by engenb** [comment]
Hey!  Sorry for the radio silence on this issue.  I can definitely give this a try in the next week or so.  I'd love to get an Argo tunnel set up with my portable K8s cluster!
