### ISSUE TITLE
Update cloudflared (argo tunnel) dependency to 2018.12.1 or higher 

### ISSUE THREAD

**Issue by mattalberts** [cloudflare/cloudflare-ingress-controller#144]
Pull forward dependent library to latest release of cloudlfared
 - https://github.com/cloudflare/cloudflared/releases

**Comment by jbergstroem** [comment]
Can we make this 2019.1.0? Looks like it contains a few things that could be related to issue we've seeing.

**Comment by mattalberts** [comment]
sure can :) . I've been looking through that version too :).  This milestone will also include tag support, which are mostly used for meta-data but sometimes they are actually feature flags .... so 0.6.3 will be able to enable the new provisioning option.
