### ISSUE TITLE
CNAME record overwritten by argo-tunnel

### ISSUE THREAD

**Issue by phroiland** [cloudflare/cloudflare-ingress-controller#167]
In my situation I have:
- `my-api` in an AKS cluster on Azure
- `my-app` on Heroku, not in a Kubernetes cluster
- Both are listed as hosts on the Ingress yaml

If I make a change to `my-api`--deleting pods, updating deployments, restarting argo-controller, etc. Argo-Tunnel refreshes the CNAMES of both. This is fine for `my-api`, but I'm forced to log into cloudflare and manually update the CNAME for `my-app` everytime. 

There should be a check to see that an alias is not **_*.cftunnel.com_** and leave it alone. 

Unless, of course, there is an annotation setting I don't know about that could keep my CNAME alias as **_*.herokudns.com_**

Other than that, even though you guys are in beta with this--it performs almost flawlessly. Pretty easy to set-up on a somewhat complicated environment like ours. Great job!

**Comment by phroiland** [comment]
With multiple environments this is really problematic.

**Comment by acrogenesis** [comment]
Why do you have my-app on the ingress yaml? Just remove it and it won't happen.

**Comment by phroiland** [comment]
You're right. Amidst my troubleshooting efforts with K8s, ingress finally working when I did include it proved to be a red herring. 

Thanks.
