### ISSUE TITLE
Docker image warp-controller:0.4.2 is not available

### ISSUE THREAD

**Issue by tbh1** [cloudflare/cloudflare-ingress-controller#23]
Currently, both the warp-controller.deployment.yaml and the helm chart reference warp-controller version 0.4.2 (quay.io/stackpoint/warp-controller:0.4.2). 

It appears that this tag does not exist.

**Comment by ntfrnzn** [comment]
Apologies for the oversight. With recent updates and name changes, the image repository is moved to gcr.io/stackpoint-public/argot, and 0.5.0 is the most recent tag.  Please note that the helm chart contains additional changes to the ingress annotation, the name of the certificate secret, the role, and the command.
