### ISSUE TITLE
The lb-pool annotation doesn't work

### ISSUE THREAD

**Issue by rishabh-bector** [cloudflare/cloudflare-ingress-controller#33]
The `argo.cloudflare.com/lb-pool: <name of lb pool>` annotation in the ingress controller definition doesn't actually set the load balancer pool name to the given one, because the flag is treated like a boolean. This means that the lb pools always use the hostname as the pool name.

**Comment by ntfrnzn** [comment]
resolved in https://github.com/cloudflare/cloudflare-ingress-controller/pull/39
