### ISSUE TITLE
Update Cloudflared (Argo Tunnel) dependency

### ISSUE THREAD

**Issue by Belphemur** [cloudflare/cloudflare-ingress-controller#34]
Hello,

From the look of it, you're not following the released of Cloudflared. This ingress controller is using cloudflared version 2018.4.7. 

The latest version is  2018.7.0.

For our use case, we would need the websocket to work, but for that to happen, the ingress would need to follow the release of the tunnel.

Can you take the time to update your dependencies and docker image version ?

**Comment by zackbloom** [comment]
Hi @Belphemur, thanks for letting us know. @ntfrnzn

**Comment by zackbloom** [comment]
Hi @Belphemur, thanks for letting us know, we are looking into it now and should have an update in the next 24 hours.

**Comment by Belphemur** [comment]
May it be linked to this issue
https://github.com/cloudflare/cloudflared/issues/36 ?

One of the dependency is not available, the server providing brotli lib is down for already a couple of days.

**Comment by ntfrnzn** [comment]
https://github.com/cloudflare/cloudflare-ingress-controller/pull/39 updates to the current cloudflared release.

Having said that, investigation into websocket behavior is ongoing.
