### ISSUE TITLE
Getting started example does not work

### ISSUE THREAD

**Issue by tonyxiao** [cloudflare/cloudflare-ingress-controller#38]
I followed the getting started tutorial in the readme and can't get the example working. 

The domain I had was the TLD associated with cloudflare account, and I used `httpbin.${mydomain.com}` as the `host` configuration in an ingress deployment file.

FWIW, when I used `cloudflared` directly to tunnel, I was able to see a dns record in my cloudflare account and it also worked. 
![image](https://user-images.githubusercontent.com/696842/44010399-00e2cd6e-9e67-11e8-9332-8bad13212f31.png)
However, no such record got created when I tried to setup argo tunnel via the ingress controller. I tried using both the TLD as well as a subdomain for the domain passed in as `cloudflare-argo/domain` and neither approach worked. 

Here are the logs from argo tunnel pod when I try to apply the ingress `kubectl create -f argo.ingress.yaml`
```
I0813 02:30:46.467708       1 controller.go:185] Annotation kubernetes.io/ingress.class=argo-tunnel
I0813 02:30:46.467780       1 controller.go:610] creating tunnel for ingress httpbin, default/httpbin/httpbin
I0813 02:30:46.476709       1 round_trippers.go:436] GET https://10.96.0.1:443/api/v1/namespaces/default/secrets/cloudflared-cert 200 OK in 8 milliseconds
I0813 02:30:46.478739       1 controller.go:636] created tunnel for ingress httpbin,  default/httpbin/httpbin
I0813 02:30:46.478779       1 controller.go:699] Validation ok for running default/httpbin/httpbin with 1 endpoint(s)
I0813 02:30:46.478841       1 controller.go:723] Starting tunnel to url httpbin.default:80
I0813 02:30:46.485156       1 round_trippers.go:436] GET https://10.96.0.1:443/apis/extensions/v1beta1/namespaces/default/ingresses/httpbin 200 OK in 6 milliseconds
I0813 02:30:46.489599       1 round_trippers.go:436] PUT https://10.96.0.1:443/apis/extensions/v1beta1/namespaces/default/ingresses/httpbin/status 200 OK in 3 milliseconds
I0813 02:30:46.489817       1 controller.go:185] Annotation kubernetes.io/ingress.class=argo-tunnel
I0813 02:30:46.489849       1 controller.go:185] Annotation kubernetes.io/ingress.class=argo-tunnel
```

And here are the logs when I delete it `kubectl delete -f argo.ingress.yaml`

```
I0813 02:31:10.058995       1 controller.go:185] Annotation kubernetes.io/ingress.class=argo-tunnel
I0813 02:31:10.059101       1 controller.go:770] Removing tunnel default/httpbin/httpbin
I0813 02:31:10.059132       1 controller.go:502] Error processing delete:default/httpbin/httpbin: lookup cftunnel.com on 10.96.0.10:53: no such host
I0813 02:31:10.064582       1 controller.go:770] Removing tunnel default/httpbin/httpbin
I0813 02:31:10.064626       1 controller.go:502] Error processing delete:default/httpbin/httpbin: Tunnel not found for key default/httpbin/httpbin
I0813 02:31:10.075053       1 controller.go:770] Removing tunnel default/httpbin/httpbin
E0813 02:31:10.075128       1 controller.go:508] Dropping object "delete:default/httpbin/httpbin" out of the queue: Tunnel not found for key default/httpbin/httpbin
```

**Comment by stephane-cloudflare** [comment]
I've got the same issue, seems like Argo is trying to open a tunnel with {serviceName}.default:{port}

**Comment by ntfrnzn** [comment]
I believe this is resolved in version 0.5.2 because of various dependency updates.  At the very least there will more logging information available.

**Comment by stephane-cloudflare** [comment]
Hey Nate,

Don't if related to this new version but my tunnels unregister after a period of time without re-initializing. Do you have an idea of what could be the reason?

**Comment by ntfrnzn** [comment]
@stephane-cloudflare I don't have an explanation for this unregistration, we'll have to dig into this more deeply.

**Comment by stephane-cloudflare** [comment]
Nevermind nate, was using the registry version with the hash tag before the 0.5.2 has been released, using the 0.5.2 tag now work as excepted! Thanks for your support,

**Comment by tonyxiao** [comment]
@ntfrnzn to confirm, if I want to expose a service running at `service.staging.tld.com`, should domain passed in as `cloudflare-argo/domain` be set to `tld.com` or `staging.tld.com`? And what should the domain in the ingress be?

**Comment by ntfrnzn** [comment]
@tonyxiao the value of `cloudflare-argo/domain` should be the same as the cloudflare site you manage at https://dash.cloudflare.com/, for instance `tld.com`.  The value specified in the ingress, (`.spec.rules[0].host`) should be `service.tld.com` 

I believe that the certificate managed by cloudflare will *not* support arbitrary multiple levels like `service.something.tld.com`

**Comment by stephane-cloudflare** [comment]
True, the Origin Certificate covers by default the APEX and wildcard at the first level so not for `service.staging.tld.com`. @tonyxiao, feel free to generate one directly through your interface in the Crypto tab for the good level you're trying to publish your application on and use this new one for your ingress controller.

**Comment by tonyxiao** [comment]
@stephane-cloudflare your suggestion worked. Thank you!

**Comment by mattalberts** [comment]
@tonyxiao I've also added a miniature walk-through/guide that should help,
 - [Agro Subdomain Tunnels](https://github.com/cloudflare/cloudflare-ingress-controller/blob/master/docs/guide_subdomain_tunnel.md)
