### ISSUE TITLE
Health checks

### ISSUE THREAD

**Issue by Maxpain177** [cloudflare/cloudflare-ingress-controller#79]
How do set up health check with multiple Argo Tunnels in LB?

**Comment by mattalberts** [comment]
@Maxpain177 You can setup health-checks as part of your load-balancer definition
 - [LoadBalancer Setup](https://support.cloudflare.com/hc/en-us/articles/115000081911-Tutorial-How-to-Set-Up-Load-Balancing-Intelligent-Failover-on-Cloudflare)

**Comment by mattalberts** [comment]
I'm going to close the issue?  I assume the link was useful. If you need more information, let me know!
